services:
  - type: web
    name: michelanglo-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "import sqlalchemy; print('SQLAlchemy version:', sqlalchemy.__version__)"
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 4
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PYTHONUNBUFFERED
        value: 1
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: FLASK_ENV
        value: production
      - key: CORS_ORIGINS
        value: https://your-production-domain.com

databases:
  - name: michelanglo-db
    databaseName: michelanglo
    user: postgres
    plan: free
    autoDeploy: true 